t = input('Digite algo')
print('O tipo primitivo desse valor é', type(t))
print('É alfa numerérico?', t.isalnum())
print('É um digito?', t.isdigit())
print('É um número?' , t.isnumeric())
print('É maiúsculo?' , t.isupper())
print('É alfabético?', t.isalpha())
print('Só tem espaços?', t.isspace())
